exclude: 'docs|node_modules|.git|.tox'
default_stages: [ commit ]
fail_fast: true

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
        exclude: ^tools/
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-added-large-files
        exclude: ^tests/data/
      - id: mixed-line-ending
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
          - flake8-docstrings
          - pep8-naming
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
      - id: mypy
