[tool.black]
line-length = 159

[tool.isort]
# https://github.com/timothycrosley/isort
# https://github.com/timothycrosley/isort/wiki/isort-Settings
line_length = 159
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
known_first_party = "ehc_api"
